### ISSUE TITLE
Error: Login failed: 

### ISSUE THREAD

**Issue by tits4net** [dbrgn/pyxtra#10]
Hello !

First, thank you for this nice job, it seems to be very usefull for me, but, i cann't do it work ...

When I login I receive : 

Error: Login failed:  

If i try with false login/password I receive : 

Error: Login failed: Der Benutzername und/oder das Passwort sind falsch.

I try to understand how I can debug this, but if I change __debug = True in pyxtra.py, it don't show me anything more ... 

So can you help me ? Do you know maybe why it don't work, or how I can try to debug it ?

Thanks a lot 
Cheers, 
TM

**Comment by dbrgn** [comment]
It works for me with both the captcha breaking mode and without it.

The message "Login failed:" only occurs if the return value of the Swisscom website does not return a valid status code.

As the program still works for me, this must be either a temporary error, or have to do with your environment. What operating system are you using?

**Comment by tits4net** [comment]
I'm using Ubuntu 9.10 so I'll try to creat another account on swisscom or something like this ... If Login Failed is a swisscom error, I'll look on this way :)

Thanks for you answer

**Comment by dbrgn** [comment]
Are you using a real Xtrazone Account or a "normal" Swisscom Account? Or in other words, can you log in to the xtrazone website?
