### ISSUE TITLE
Contact SMS Mode

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/pyxtra#11]
Create a mode like the normal sms mode (using n!), but remember the recipient and don't query for the recipient each time a new sms is sent. Could be called something like "receiver lock". Accessed by entering "n!!".

**Comment by petermanser** [comment]
great idea, want to have that too. :)

**Comment by dbrgn** [comment]
then code it :P

**Comment by petermanser** [comment]
same to you :P
