### ISSUE TITLE
Pyxtra crashes if address book is empty

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/pyxtra#15]

**Comment by dbrgn** [comment]
Can someone confirm this?

**Comment by petermanser** [comment]
@gwrtheyrn, please contact the reporter of the bug and ask him to review/test it. Thanks.

**Comment by dbrgn** [comment]
@petermanser guess what i did this afternoon...

**Comment by petermanser** [comment]
@gwrtheyrn feedback?

**Comment by petermanser** [comment]
@gwrtheyrn ping. feedback?
