### ISSUE TITLE
Autoslicing messages larger than 440 chars

### ISSUE THREAD

**Issue by tannerli** [dbrgn/pyxtra#17]
Would it be possible to automatically split up large messages into multiple sms? Would be nice, especially when you wrote your 440+ chars text and are being told it's too big and you have to start over.

An option in the configfile would seem nice...

**Comment by petermanser** [comment]
good idea. :)

**Comment by dbrgn** [comment]
You don't have to start over, just press the "up" button and fix it.

But it's a good idea. Given that a user has to confirm, when an SMS uses up more than 3(?) SMS credits. Also, if slicing happens, it should be indicated.

**Comment by petermanser** [comment]
Let's change the error "Too long" to a confirmation "Send it anyway"!?

**Comment by dbrgn** [comment]
Yes, that would be a possibility. But the logic needs to be changed a littlebit, so that the slicing can occur.

Examples:
- This message will eat up 3 SMS credits. Send it anyway? [Y/n]
- This message is very long. It will be sent in 3 separate SMS and will eat up 17 SMS credits. Send it anyway? [Y/n]

**Comment by petermanser** [comment]
Why would you ask if it needs 3 credits? (Asking if >1 credit?)
I'd need a setting where I can say "force sending" then. (I don't care about credits :))

**Comment by dbrgn** [comment]
I'd ask if it needs >2 credits.

Let's call the setting "never ask". :)

**Comment by petermanser** [comment]
Scenario 1 (config not set yet):

> $ pyxtra 
> Do you want to send sms automatically, even if they are longer than 440 chars? (Y/n)

Scenario 2 (auto_send_long_sms = yes):

> > n
> Receiver(s): Peter Manser
> Message: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> SMS sent successfully.
> SMS sent successfully.
> SMS sent successfully.
> SMS sent successfully.
> 98 SMS remaining.

Scenario 3 (auto_send_long_sms = no):

> > n
> Receiver(s): Peter Manser
> Message: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> Message is 446 characters long. Do you want to send it anyway? (Y/n) 
> SMS sent successfully.
> SMS sent successfully.
> 94 SMS remaining.

**Comment by petermanser** [comment]
Gerade gesehen, dass ich das logging kaputt gemacht habe. :S

**Comment by petermanser** [comment]
Fixed. Bitte um review/testing... :)

**Comment by tannerli** [comment]
Getestet, sieht gut aus... allerdings macht jetzt (oder schon länger.. kA) die Kontakt-autovervollständigung ein Komma hinter den Namen.... also
Mar [TAB]   wird zu Marco Tanner ,

was dann beim Senden  zu einem 
Error, Unknown Error sending SMS und Programmabbruch führt... 

weiss nicht ob das Zusammengehört oder ob das ein separates Issue sein sollte

**Comment by petermanser** [comment]
Das hab ich gestern noch eingebaut, dass man besser autocompleten kann.. Und das Komma sollte er egtl. wieder weg strippen vor dem senden... Hab ich egtl. gestern noch getestet.. :S

**Comment by petermanser** [comment]
Ach... ich habe irgendwie noch vor dem committen was rumgefummelt gestern. Fixed now. Sorry.

**Comment by tannerli** [comment]
Irgendwie funktionieren Umlaute nicht mehr...

> n
> Receivers: Marco Tanner, 
> Message:   ä
> Error: 'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)

Ich vermute das Problem hier... sorry wenn ich so nervig bin ;-)

479     # Get message text
480     while not message:
481         message = unicode(raw_input('Message:   ').strip(), 'utf-8')

**Comment by dbrgn** [comment]
Problem ist bekannt, ist ja auch noch nicht ganz fertig :) Danke trotzdem für den Hinweis.

**Comment by dbrgn** [comment]
@tannerli fixed, siehe #19
