### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by petermanser** [dbrgn/pyxtra#20]
Following do work:
07XXXXXXXX
07X XXX XX XX
00417X XXX XX XX

Following should work, but don't:
+41 7X XXX XX XX
+41 7X XXX XX XX

Basically the plus should be accepted. :)

**Comment by dbrgn** [comment]
Xtrazone does not accept int. format numbers directly. We need to strip the
+41/0041 part.
Am 11.09.2011 19:43 schrieb "Peter Manser" <
reply@reply.github.com>:

**Comment by petermanser** [comment]
Yes it does. Just tried it.

**Comment by dbrgn** [comment]
Ah, you're right. But + is not accepted in the address book.

We should simply strip out 0041 / +41 whenever it gets entered in pyxtra. The address book only saves 07x and 4107x numbers anyways.

**Comment by petermanser** [comment]
Strip out the + (everywhere) would solve the problem, right?

**Comment by dbrgn** [comment]
Yes, but as I said before, strip out the entire 41/+41/0041, the numbers look better that way, and international numbers don't work anyways.

**Comment by petermanser** [comment]
pyxtra crashes, if you would just strip the *41 away.
Receivers: 791234567
Message: foobar.
Error: Unknown error sending SMS.

 I'm not sure if we should really strip it and add a 0 instead. why is the 41 in front of the number so wrong. xtrazone shows the contact in the address book in this format.
1) http://o7.no/p4QhjQ
2) http://o7.no/qdTKKq

**Comment by dbrgn** [comment]
I was talking about replacing it with a 0, of course.
- The result is exactly the same.
- 4179... is not a valid phone number format.
- 079... Looks more familiar. 
- You can't send sms to international numbers anyways

**Comment by petermanser** [comment]
okay. let's enforce the format 0791234567 everywhere.
- Spaces are allowed and striped.
- 41/+41/0041 will be replaced by a "0"

Agreed?

**Comment by dbrgn** [comment]
Yes. :)

**Comment by tannerli** [comment]
Xtrazone accepts the following
^(((((\+|00)?41)|0)7(6|7|8|9))|((\+|00)?423))\d{7}$ //Copied out of JS-code straight from xtraZone itself...

**Comment by petermanser** [comment]
@gwrtheyrn go and fix it.
