### ISSUE TITLE
Accept contact name as receiver

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/pyxtra#3]
- Instead of having to type a phone number to define the receiver, accept a string and try to match a contact
- If several people match, list them
- Tab completion would be great but not that important

**Comment by dbrgn** [comment]
Solved by providing contacts tab completion (yeah!). Several contacts can be separated with a comma.

Not sure whether that works on a Mac and probably won't work on Windows. Peter, if it works on your macbook, please close this issue.

**Comment by petermanser** [comment]
Awesome. Works now.
