### ISSUE TITLE
Dependency missing in Readme

### ISSUE THREAD

**Issue by mhutter** [dbrgn/pyxtra#8]
The following dependency is not listed in the Readme-file:
- ImageTk (python-imaging-tk)

Error Message was:
    u10:~ $ pyxtra.py
    Python module me ImageTk not found. Install it using pip or your system's package manager.
    u10:~ $ sudo aptitude install python-imaging-tk
    _snipp_
    u10:~ $ pyxtra.py 
    Could not find configuration file. Creating /home/user/.pyxtra/config.
    ...

**Comment by dbrgn** [comment]
This is probably Debian/Ubuntu that separates the PIL package into several subpackages. If you install PIL from the Python package sources, it will contains ImageTk too.

I will add a note in the README file.

**Comment by mhutter** [comment]
Yep, unfortunately it's a new bad habit from the Deb/Ubuntu Guys to split up every package...

**Comment by dbrgn** [comment]
Improved README (closed by 4808efed12b3b11d73bff17c85b4ec11a98a1258)
